### ISSUE TITLE
Support programatically constructing outputs

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#102]
I've been thinking about a way we could make stacker -> empire conf simpler.

Right now I setup the stacks, then have to examine the outputs (mostly just DB addresses) and map them to DATABASE_URL and REDIS_URL values in an empire conf. I think something like this could be useful:

```
  - name: apiRdsDb
    class_path: stacker.blueprints.rds.postgres.MasterInstance
    locked: true
    parameters:
      << : *vpc_parameters
      ... db parameters ...
    outputs:
      DATABASE_URL:
        - path: stacker.outputs.construct_database_url
          args:
            username: ${api_rds_master_user}
            password: ${api_rds_master_user_password}
            hostname: apiRdsDb::DBAddress
            datbase: ${api_rds_db_name}
```

then maybe some flag to `stacker info` could output all of the "outputs" you've defined in the config, ie.

```
DATABASE_URL=postgres://user:password@hostname/dbname
```

that could be appended to an existing env file or be the start of an env file you load within empire via `emp env-load`
