### ISSUE TITLE
Allow for sub-tree provisioning

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#186]
If we think about it, stacker configs are just a dependency tree (a DAG to be exact), where stacks depend on other stacks. It would be useful if you had the ability to start provisioning from an explicit root.

For example, say I have the following stacker config:

``` yaml
stacks:
  - name: vpc
  - name: bastion
    parameters:
      VpcId: vpc::Id
  - name: db
    parameters:
      VpcId: vpc::Id
  - name: api
    parameters:
      DatabaseUrl: db::Url
```

It would be handy to be able to specify the starting point for provisioning, like:

``` console
$ stacker build --root api
api -> db -> vpc
```

``` console
$ stacker build --root bastion
bastion -> vpc
```

I think this would be more powerful than the current `--stacks` flag, since that currently doesn't respect dependencies.
