### ISSUE TITLE
Ability to dynamically add variables

### ISSUE THREAD

**Issue by ttarhan** [remind101/stacker#224]
Hey guys,

I have another use case that used to work with the old local_parameters setup, that (possibly) breaks with the new variables implementation. Bear with me, because this is probably a unique usage of Stacker, but it's super helpful:

Both @troyready and I work in an environment where we're sometimes required to produce "pure" CloudFormation templates. In these environments, Stacker has still been useful to build/export the templates. However, this requires exclusively using CFN Params and not runtime-compiled variables. Your help in adding CFNType support to the variable system has ensured this use case continues to work for us, EXCEPT one trick:

I currently leverage the fact that local_parameters are handled before normal (old style) parameters to dynamically add more parameters. Specifically, I use this where we have a blueprint that's very generic and could be used in many cases, and each usage of the blueprint requires a custom set of security groups and/or EC2 tags. In other words, when developing the blueprint, we don't know **how many** security groups and/or tags are needed, and since CFN is braindead in it's (lack-of sane) list handling for these properties, we use a trick like this:

```
    LOCAL_PARAMETERS = {
        "OtherTagNames": {
            "type": list,
            "default": [],
        },
        "OtherSGNames": {
            "type": list,
            "default": [],
        },
```

Then, we override _get_parameters as such:

```
    def _get_parameters(self):
        params = super(ClusterInstance, self)._get_parameters().copy()

        for tagName in self.local_parameters["OtherTagNames"]:
            params[tagName] = {
                "type": "String",
                "description": ("Extra tag value with the name %s to apply to the instances" % tagName)
            }

        for sgName in self.local_parameters["OtherSGNames"]:
            params[sgName] = {
                "type": "String",
                "description": ("Extra security group for %s to apply to the instances" % sgName)
            }

        return params
```

Then we use these in the blueprint:

```
        t.add_resource(
            ec2.Instance(
                "Instance",
                ImageId=Ref("AmiId"),
                InstanceType=Ref("InstanceType"),
                KeyName=If("UseSshKey", Ref("SshKeyName"), Ref("AWS::NoValue")),
                SubnetId=Ref("Subnet"),
                UserData=user_data,
                BlockDeviceMappings=block_device_mappings,
                SecurityGroupIds=[
                    Ref("ClusterSG")
                ] + [
                    Ref(sgName) for sgName in self.local_parameters["OtherSGNames"]
                ],
                IamInstanceProfile=Ref("InstanceProfile"),
                Tags=[
                    ec2.Tag("Name", Ref("AWS::StackName"))
                ] + [
                    ec2.Tag(tagName, Ref(tagName)) for tagName in self.local_parameters["OtherTagNames"]
                ]
            )
        )
```

This basically allows us to specify a list of additional tag names or security group names (where name here means a label for the usage), but specify their values (the actual tag value or the actual group ID) as a CFN Param that can be modified without re-generating the template.

We use this in a config like this:

```
  - name: esmaster
    class_path: blueprints.sturdy.clusterinstance.ClusterInstance
    parameters:
      Subnets: ${Subnets}
      InstanceProfile: base::InstanceProfile
      ClusterSG: base::ClusterSG
      MinInstances: 2
      MaxInstances: 2
      DesiredInstances: 2
      OtherTagNames:
        - EsCluster
        - EsRole
      OtherSGNames:
        - EsClientSG
      EsCluster: ${ClusterName}
      EsRole: master
      EsClientSG: base::ClientSG
```

This ends up adding EsCluster and EsRole as tags, and EsClientSG as an additional security group to the Instance. Essentially, it enables a super generic ClusterInstance (we also have ClusterAsg) blueprint to be used for a ton of different use cases.

Thoughts?
