### ISSUE TITLE
Support using troposphere objects as blueprints

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#249]
I was writing a blueprint for s3 which essentially was just collecting values to pass to troposphere's s3 bucket object.

For these simple cases, maybe we can just do something like:

```
- name: someBucket
   class_path: troposphere.s3.Bucket
   variables:
     BucketName: ${bucket_name}
     AccessControl: PublicRead
     Tags:
        - myS3Bucket
```

which would essentially just do something like:

```
from troposphere.s3 import Bucket


class TroposphereBlueprint(Blueprint):
    def create_template(self):
        t = self.template
        variables = self.get_variables()
        t.add_resource("Resource", Bucket.from_dict(variables))
```

we would need to adjust some things to support that, but I like the idea of just piping variables to `from_dict` in troposphere since @phobologic added support for creating the objects from dicts.

I'm not a fan of having `class_path` map to both blueprints and troposphere objects like the above, maybe we can roll out a concept of "drivers" for v1? @phobologic has talked about this, but not sure what it would look like yet.

Thoughts?
