### ISSUE TITLE
KMS cipher texts throw off lookup parsing?

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#250]
In an number of places, I'm doing this:

``` yaml
# conf
variable: us-east-1@AQEC...fQ==
```

``` yaml
# stack.yaml
- name: stack
   variables:
     Thing: ${kms ${variable}}
```

Depending on the value of the ciphertext, sometimes I'll get what I expect (the unencrypted plain text) and sometimes I'll get this in the template:

```
${kms us-east-1@AQEC...fQ==}
```

It seems to only happen when the ciphertext includes `==`, so maybe that's throwing off [lookup.LOOKUP_REGEX](https://github.com/remind101/stacker/blob/5a62de834bc74bce7e2a0ce64e2ad35eba5ddec7/stacker/lookups/__init__.py#L9-L18)?
