### ISSUE TITLE
Feature: Cross account management

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#263]
Just jotting this down here to make note of it. It'd be pretty cool if stacker could link cross account stacks. For example, if most of your resources are managed in account A, you may want to add an account B that's 100% isolated from account A, then give account A access to AssumeRole into B. Being able to manage resources via stacker in both A and B would be pretty rad.

I'm not sure the best way to do it, but it could integrate with AWS profiles, so you could tag certain stacks with a certain profile. e.g.

```yaml
stacks:
  - name: vpc
     profile: A
  - name: emr
     profile: B
  - name: app
     profile: A
     variables:
       EMRAssumeRole: ${emr::Role}
```
