### ISSUE TITLE
Configure region outside of the CLI?

### ISSUE THREAD

**Issue by rouge8** [remind101/stacker#277]
It would be great if we could specify the region when configuring stacks, e.g.:

```yaml
stacks:
  - name: app-us-west
    class_path: my_blueprints.App
    region: us-west
  - name: app-us-east
    class_path: my_blueprints.App
    region: us-east
```

**Comment by phobologic** [comment]
I wonder if this would be a good idea to combine w/ #263.  Maybe make a profile a mix of account id + region?

**Comment by phobologic** [comment]
@ejholmes ping ^^

**Comment by ejholmes** [comment]
Yep, I think it'd make sense to just add support for specifying what profile to use when creating a stack. That'd easily allow for cross account/region/etc use cases, as well as all the other stuff that profiles allow, like assuming rules + mfa.

For example, in the case above, you can just point stacker at an `~/.aws/config` file like:

```
[profile "infra-east"]
region = us-east-1

[profile "infra-west"]
region = us-west-1
```

And then specify the profile in the stacks definition:

```yml
stacks:
  - name: app-us-west
    class_path: my_blueprints.App
    profile: infra-west
  - name: app-us-east
    class_path: my_blueprints.App
    profile: infra-east
```
