### ISSUE TITLE
Convert floats to strings in the YAML files 

### ISSUE THREAD

**Issue by ttaub** [remind101/stacker#291]
Similarly to issue: #290

Stacker should be smart enough to be able to parse floats in the configuration files.

**Comment by jeshan** [comment]
Another example of issue:
```yaml
      - PolicyDocument:
          Statement:
          - Action:
            - ecr:*
            Effect: Allow
            Resource: '*'
          Version: 2012-10-17
        PolicyName: name
```

2012-10-17 is interpreted as a python datetime. it should be interpreted as string. Quoting the 2012-10-17 works.


```yaml
      - PolicyDocument:
          Statement:
          - Action:
            - ecr:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: name
```
