### ISSUE TITLE
Allow nested lookups

### ISSUE THREAD

**Issue by oliviervg1** [remind101/stacker#356]
Given the following Stacker yaml:

```
  - name: dns
    class_path: route53.RecordSet
    variables:
      DNS: foobar.com.
      Type: A
      Destination: ${asg_private_ip ${output foobar_autoscaling_group::AsgId}}
```

We get the following stacktrace:
```
stacker.exceptions.FailedVariableLookup: Couldn't resolve lookups in variable `Destination`. handler() takes exactly 1 argument (0 given)
```

It would be great if we could nest lookups such that the result from `output` gets passed into `asg_private_ip`.
