### ISSUE TITLE
Support for stack-level tags

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#395]
At the moment, you can provide a global set of tags that get applied to all stacks in a stacker config, but it would be handy to be able to be able to specify stack specific tags as well. For example:

```yaml
tags:
  environment: ${environment}

stacks:
- name: apiDB
   tags:
     service: api
```
