### ISSUE TITLE
RFC: blueprint acquisition system

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#41]
Right now it's kind of annoying to use third party blueprints in stacker - you have to get them (git pull), then install them in your python path (python setup.py install), only then can you use them.

I'm trying to think of a better way to do this, so opening this up for discussion from 'the community' :)

**Comment by phobologic** [comment]
One idea is to do something like golang's import system:

```
github.com/phobologic/myblueprints/myblueprints/cool_blueprint.CoolBlueprint
```

Then make it so that stacker pulls that file down (ending with .py, the CoolBlueprint part is the class), puts it in a temp directory, then adds that temp directory to your python path while it tries to import the blueprints.

**Comment by mhahn** [comment]
i vote for:

- current working directory gets appended to sys.path so you can access local blueprints
- i agree with something like the above, although i would maybe push for something similar to a Gemfile:

```
# conf/example.yaml

stacks:
  - name: coolBluePrint
    blueprint:
      git: github.com/phobologic/myblueprints
      path: myblueprints.cool_blueprint.CoolBlueprint
```

i think that gives you more control than just having something like "blueprint: github.com/phobologic/myblueprints/myblueprints/cool_blueprint.CoolBlueprint" or "blueprint: stacker.blueprints.vpc.VPC", and having the logic be driven by the prefix of blueprint.

i would rather have something more verbose that gives you more room to expand it in the future.

i would also want to account for something like we did for empire stacks where the blueprint used other python files, ie "policies.py", which means more than just downloading 1 file.

**Comment by brianz** [comment]
Either of those would work.  Another alternative is to set a list of directories where Stacker would look for blueprints...set in the yaml file:

```
blueprint_dirs:
    - ~/path/to/blueprints
    - ../another/path/to/blueprints
```

That coupled with the ideas above could work well...i'd also suggest changing some names...`source` and `class` to be more general and specific, respectively:

```
stacks:
  - name: coolBluePrint
    blueprint:
      # Only look in this repo for this blueprint
      source: github.com/phobologic/myblueprints
      class: myblueprints.cool_blueprint.CoolBlueprint
  - name: cache
    blueprint:
      # this would look through the set of blueprint_dirs, in addition to any default dirs
      class: sekrt.elasticache.ElasticCache
```
