### ISSUE TITLE
Documentation issue regarding TroposhereType

### ISSUE THREAD

**Issue by russellballestrini** [remind101/stacker#481]
Our documentation regarding how to pass stack config for a `TroposphereType` is invalid for 
`AWSResource` but valid for `AWSProperty`.

The `AWSResource` objects require a title so we have to nest them the same way we nest the "many" case.

Reference: https://stacker.readthedocs.io/en/latest/blueprints.html#example

**Comment by phobologic** [comment]
@russellballestrini It's just the example config that is wrong, correct?  This part in particular:

```
      SingleBucket:
        BucketName: my-single-bucket
```

?

**Comment by russellballestrini** [comment]
Yes.  For example (https://github.com/remind101/stacker_blueprints/blob/master/stacker_blueprints/aws_lambda.py#L230-L237)

I initially tried the following stack config:

```
  - name: autospotting-schedule
     class_path: blueprints.aws_lambda.FunctionScheduler
     variables:
       CloudwatchEventsRule:
         Description: The AWS Lambda schedule for autospotting
         ScheduleExpression: "rate(5 minutes)"
         State: ${autospotting_schedule_state}
         Targets:
           - Id: autospotting-schedule-for-${environment}
             Arn: ${output autospotting::FunctionArn}
```

But I had to do this instead:

```
  - name: autospotting-schedule
     class_path: blueprints.aws_lambda.FunctionScheduler
     variables:
       CloudwatchEventsRule:
         AutospottingSchedule:
           Description: The AWS Lambda schedule for autospotting
           ScheduleExpression: "rate(5 minutes)"
           State: ${autospotting_schedule_state}
           Targets:
             - Id: autospotting-schedule-for-${environment}
               Arn: ${output autospotting::FunctionArn}```
